version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE=on
    working_directory: /go/wd
    steps:
      - checkout

      - run: go test -race -v ./...
